 NumPy es una herramienta fundamental en ciencia de datos debido a su eficiencia, capacidad de cálculo matemático y su integración con otras bibliotecas. Proporciona una base sólida para muchas tareas, como el procesamiento y análisis de datos, la simulación numérica, la implementación de algoritmos de aprendizaje automático y más.

In [ ]:
import numpy as np



1.- ARRAYS BASICOS


In [ ]:
#como crear un array basico

a = np.array([1,2,3])

a

array([1, 2, 3])

In [ ]:
#crear un array de ceros

a=np.zeros(3)

a

array([0., 0., 0.])

In [ ]:
#crear un array de unos
a=np.ones(4)

a


array([1., 1., 1., 1.])

In [ ]:
#crear un array con elementos elegidos al azar

a=np.random.rand(4,3)


a

array([[0.96211957, 0.3412075 , 0.1097626 ],
       [0.41249065, 0.95681595, 0.54791781],
       [0.20813066, 0.87322138, 0.8038373 ],
       [0.25884928, 0.20943185, 0.02610551]])

In [ ]:
#La función empty en NumPy se utiliza para crear un
#nuevo arreglo multidimensional sin asignar ningún
#valor inicial a sus elementos.

#La función empty reserva espacio en la memoria para
#el arreglo, pero no inicializa los valores de sus elementos.

#Un ejemplo práctico de uso de empty sería cuando se necesita crear un
#arreglo con dimensiones específicas, pero los valores iniciales no son
#relevantes en ese momento y se van a sobrescribir más adelante en el código.

aa=np.empty((3, 4))

aa

array([[0.96211957, 0.3412075 , 0.1097626 , 0.41249065],
       [0.95681595, 0.54791781, 0.20813066, 0.87322138],
       [0.8038373 , 0.25884928, 0.20943185, 0.02610551]])

In [ ]:
arr=np.empty(5)

arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#crear un array con un rango de elementos
a=np.arange(5)

a

array([0, 1, 2, 3, 4])

In [ ]:
#crear un array con un rango de intervalos parejos, primer numero(2), ultimo
#numero(16)

a=np.arange(2, 16)

a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
#al ejercicio anterior le añadimos un salto de 6
a=np.arange(0, 17, 6)

a

array([ 0,  6, 12])

In [ ]:
#para crear un array con valores que estan espaciados linealmente dentro de un
#rango especificado, vemos que el output es diferente al del ejercicio anterior

a=np.linspace(0, 17, 8)

a

array([ 0.        ,  2.42857143,  4.85714286,  7.28571429,  9.71428571,
       12.14285714, 14.57142857, 17.        ])

In [ ]:
#podemos especificar el data type con el metodo dtype

a= np.linspace(0, 17, 25).round(4)

a

array([ 0.    ,  0.7083,  1.4167,  2.125 ,  2.8333,  3.5417,  4.25  ,
        4.9583,  5.6667,  6.375 ,  7.0833,  7.7917,  8.5   ,  9.2083,
        9.9167, 10.625 , 11.3333, 12.0417, 12.75  , 13.4583, 14.1667,
       14.875 , 15.5833, 16.2917, 17.    ])

2.-ORDENAR, QUITAR Y AÑADIR ELEMENTOS EN UN ARRAY

In [ ]:
#con la funcion np.sort() podemos ordenar el array


a= np.array([2, 1, 5, 3, 7, 4, 6, 8])

np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#si queremos orden descendente

a=np.array([2, 1, 5, 3, 7, 4, 6, 8])

np.sort(a)[::-1]



array([8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
#si queremos ordenar una array multidimensional a lo largo del eje 0 (columnas)

# el segundo : es para seleccionar todas las columnas
a=np.array([[5, 2, 8], [1, 3, 6]])

a


array([[5, 2, 8],
       [1, 3, 6]])

In [ ]:
np.sort(a, axis=0)

array([[1, 2, 6],
       [5, 3, 8]])

In [ ]:
#si usamos el axis=1
a=np.array([[5, 2, 8], [1, 3, 6]])

np.sort(a, axis=1)

array([[2, 5, 8],
       [1, 3, 6]])

In [ ]:
#para hacerlos en orden descendente podemos hacerlo asi
a=np.array([[5, 2, 8], [1, 3, 6]])

np.sort(a, axis=1)[:, :: -1]

array([[8, 5, 2],
       [6, 3, 1]])

In [ ]:
#podemos concatenar arrays
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

c= np.concatenate((a,b))

c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#otro ejemplo de concatenado pero ahora multidimensional

x=np.array([[1, 2], [3, 4]])
y=np.array([[5, 6], [7, 8]])

z=np.concatenate((x,y), axis=0)

z

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
#en vez de usar el axis cero vamos a usar el axis 1
x=np.array([[1, 2], [3, 4]])
y=np.array([[5, 6], [7, 8]])

z=np.concatenate((x,y), axis=1)

z


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
#para eliminar elementos de un array usamos el metodo delete()
#este metodo usa 3 argumentos: el array de entrada, los indices de los
#elementos a eliminar y el eje a los largo del cual se hace la eliminacion

a=np.array([1, 2, 3, 4, 5])

np.delete(a, [1, 3])  #elimina el segundo y cuarto elemento del array

array([1, 3, 5])

In [ ]:
#si el array es multimensional debemos especificar el eje a lo largo del cual
#eliminamos los elementos

a=np.array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])

np.delete(a, 2, axis=1)  #elimina la segunda columna del array

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
#otro ejemplo
a=np.array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])

np.delete(a, 1, axis=0)  #elimina la segunda fila del array

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
#para añadir elementos a un array podemos usar el metodo append()
#de nuevo este metodo usa 3 argumentos, el array de entrada, los elementos
#a añadir y el eje a lo largo del cual se añaden

a= np.array([1, 2, 3])

np.append(a, [4, 5])



array([1, 2, 3, 4, 5])

In [ ]:
#para arrays multidimensionales debemos especificar el eje a lo largo
#del cual se añadiran los elementos nuevos

a= np.array([[1, 2, 3],
             [4, 5, 6]])

np.append(a, [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#si deseamos añadir nuevos elementos a un array de Numpy en una posicion
#especifica debemos usar el metodo insert(), necesita 3 argumentos
#el array de entrada, el indice de la posicion de insercion y los elementos
#a añadir

a= np.array([1, 2, 3, 4, 5])

np.insert(a, 4, 33) #inserta el numero 33 en la posicion 4 del array

array([ 1,  2,  3,  4, 33,  5])

In [ ]:
#tambien podemos insertar elementos nuevos en arrays multidimensionales de forma
#parecida a los ejercicios anteriores

a= np.array([[1, 2, 3],
             [4, 5, 6]])

np.insert(a, 1, [0, 0], axis=1)  #esta vez no me pide doble corchete como en el
#ejercicio de antes



array([[1, 0, 2, 3],
       [4, 0, 5, 6]])

3.- COMO SABER LA FORMA, TAMAÑO Y DIMENSION DE UN ARRAY

In [ ]:
#como saber la forma y el tamaño del array
#ndarray.ndim
#ndarray.size
#ndarray.shape

In [ ]:
#para saber las dimensiones de un array( numero de ejes o dimensiones
#que tiene el array)
a=np.array([1, 2, 3])

a

array([1, 2, 3])

In [ ]:
a.ndim

1

In [ ]:
a=np.array([[1, 2, 3], [4, 5, 6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.ndim

2

In [ ]:
a=np.array([[[0, 1, 2, 3],
             [4, 5, 6, 7]],

           [[0, 1, 2, 3],
            [4, 5, 6, 7]],

           [[0, 1, 2, 3],
            [4, 5, 6, 7]]])

a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [ ]:
a.ndim

3

In [ ]:
#para saber el numero total de elementos de un array

a= np.array([1, 2, 3, 4, 5, 6])
a.size

6

In [ ]:
#la diferencia entre ndim y shape es que ndim muestra un entero que
#representa la cantidad de dimensiones del array y shape devuelve una
#tupla que especifica la longitud de cada dimension del array
a= np.array([1, 2, 3, 4, 5])

a

array([1, 2, 3, 4, 5])

In [ ]:
a.shape

(5,)

In [ ]:
a=np.array([[1, 2, 3, 3], [4, 5, 6, 6]])

a

array([[1, 2, 3, 3],
       [4, 5, 6, 6]])

In [ ]:
a.shape

(2, 4)

In [ ]:
a=np.array([[[1, 2, 3, 3], [4, 5, 6, 6]],[[7, 8, 9, 9], [10, 11, 12, 12]]])

a

array([[[ 1,  2,  3,  3],
        [ 4,  5,  6,  6]],

       [[ 7,  8,  9,  9],
        [10, 11, 12, 12]]])

In [ ]:
a.shape

(2, 2, 4)

4.- RESHAPE UN ARRAY

In [ ]:
#el metodo arange crea un array unidimensional con valores espaciados
#de manera uniforme dentro de un rango especificado

a= np.arange(6)

a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a=np.arange(9).reshape(3,3)

a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a=np.arange(0, 8)

a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
a=np.arange(0, 20, 4)

a

array([ 0,  4,  8, 12, 16])

In [ ]:
#El metodo reshape se usa para cambiar la forma de un array multidimensional
#sin modificar sus datos subyacentes,La nueva forma debe ser compatible con
#la cantidad total de elementos del array original

#Tambien sirve para preparar datos para el análisis: En el procesamiento de
#datos, es común tener que reformatear los datos para que se ajusten a un
#determinado modelo o algoritmo.

#Tambien se usa para trabajar con imágenes: En el caso de imágenes, es común
#representarlas como arreglos multidimensionales. Por ejemplo, una imagen en
#escala de grises puede ser representada como una matriz 2D, mientras que una
#imagen en color puede ser representada como una matriz 3D
a= np.arange(12)

a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
#puedes cambiar la matriz a otra 3x4 o a otra 2x6
b= a.reshape(3,4)

b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
#crear un array de 4 dimensiones
d = np.arange(72)

d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71])

In [ ]:
c = np.reshape(d, (4,3,2,3))

c

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]],


       [[[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]],

        [[48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65]],

        [[66, 67, 68],
         [69, 70, 71]]]])

In [ ]:
#como convertir un array de 1D en otro de 2D. Como añadir un nuevo axis
#a un array  newaxis  expand_dims

a=np.array([1, 2, 3, 4, 5, 6])

a.shape

(6,)

In [ ]:
#puedes usar newaxis para añadir un nuevo axis
a2=a[np.newaxis, :]
a2.shape

(1, 6)

In [ ]:
#tambien puedes expandir el array insertando un nuevo axis en una
#posicion especifica, por ejemplo posicion 1

a=np.array([1, 2, 3, 4, 5, 6])

a.shape

(6,)

In [ ]:
b=np.expand_dims(a, axis=1)

b.shape

(6, 1)

In [ ]:
c=np.expand_dims(a, axis=0)
c.shape

(1, 6)

5.- INDEXING AND SLICING

In [ ]:
#Se parece al indexado y el slicing que haciamos en Python

data= np.array([1, 2, 3, 4, 5])

data[1]

2

In [ ]:
data[1:4]

array([2, 3, 4])

In [ ]:
data[3:]

array([4, 5])

In [ ]:
data[-4:]

array([2, 3, 4, 5])

In [ ]:
#podemos mostrar los valores del array que son menores a 5, en este caso nos
#muestra booleanos

a= np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a<=5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [ ]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [ ]:
#o mostrar los numeros iguales o mayores que 5

cinco= (a>=5)
a[cinco]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#o mostrar numeros divisibles por 2

divisible= a[a%2==1]
divisible

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
divisible= a[a%2!=0]

divisible

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
#tambien podemos usar el & y el |

c= a[(a>2) & (a<11)]

c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
c=(a>5) | (a==5)

a[c]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

6.- COMO CREAR UN ARRAY DE OTRO ARRAY YA EXISTENTE

In [ ]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr1= a[3:8]

arr1

array([4, 5, 6, 7, 8])

In [ ]:
#tambien puedes apilar varios arrays verticalmente u horizontalmente

a1= np.array([[1, 1],
             [2, 2]])

a2= np.array([[3, 3],
              [4, 4]])

In [ ]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
#tambien puedes dividirlos en varios arrays mas pequeños, puedes especificar
#el numero de arrays iguales

x= np.arange(1, 49).reshape(4, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]])

In [ ]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16],
        [25, 26, 27, 28],
        [37, 38, 39, 40]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20],
        [29, 30, 31, 32],
        [41, 42, 43, 44]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24],
        [33, 34, 35, 36],
        [45, 46, 47, 48]])]

In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Dividimos el array horizontalmente en dos partes
result = np.hsplit(arr, 2)

# Imprimimos los resultados
print("Array original:")
print(arr)

print("\nResultado de hsplit():")
print(result)

Array original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Resultado de hsplit():
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [ ]:
#si quieres separarlo despues de la tercera y cuarta columna

np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15],
        [25, 26, 27],
        [37, 38, 39]]),
 array([[ 4],
        [16],
        [28],
        [40]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [29, 30, 31, 32, 33, 34, 35, 36],
        [41, 42, 43, 44, 45, 46, 47, 48]])]

7.- OPERACIONES BASICAS CON ARRAYS

In [ ]:
#sumar
arr1= np.array([1, 2])

arr1

array([1, 2])

In [ ]:
arr2= np.ones(2, dtype=int)
arr2

array([1, 1])

In [ ]:
arr1+arr2

array([2, 3])

In [ ]:
#restar
arr1 - arr2

array([0, 1])

In [ ]:
#multiplicar
arr1*arr1

array([1, 4])

In [ ]:
#dividir
arr1/arr1

array([1., 1.])

In [ ]:
#para sumar los elementos de un array
a= np.array([1, 2, 3, 4])

a.sum()

10

In [ ]:
#para sumar las columnas en un array 2D debemos especificar el axis

b= np.array([[1, 1], [2, 2]])

b

array([[1, 1],
       [2, 2]])

In [ ]:
#Puedes sumar sobre el eje de columnas
b.sum(axis=0)

array([3, 3])

In [ ]:
#Puedes sumar sobre el eje de filas
b.sum(axis=1)

array([2, 4])

In [ ]:
#tambien podesmos multiplicar un array por un numero (se llama broadcast
#en ingles)

data= np.array([1.0, 2.0, 3.0, 4.0, 5.0])

data*1.6

array([1.6, 3.2, 4.8, 6.4, 8. ])

In [ ]:
#otras operaciones
data.max()

5.0

In [ ]:
data.min()

1.0

In [ ]:
data.sum()

15.0

In [ ]:
data.mean()

3.0

In [ ]:
#para multiplicar todos los elementos entre ellos
data.prod()

120.0

In [ ]:
#para calcular la desviacion standard
data.std()

1.4142135623730951

In [ ]:
#para culcular la desviacion standard de numeros muy dispersos

a= np.array([1, 15, 60, 390, 550, 34, 7, 342, 100])
a.mean()

166.55555555555554

In [ ]:
a.std().round(4)

193.4851

8.- MAS EJERCICIOS CREANDO MATRICES

In [ ]:
#Puedes pasar listas de listas de Python para crear un array 2D(matriz)
import numpy as np
data=np.array([[1, 2], [3, 4], [5,6]])

data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#vamos a practicar un poco de slicing con esta matriz
data[0, 1]

2

In [ ]:
data[0:2]

array([[1, 2],
       [3, 4]])

In [ ]:
data[0:3, 0]

array([1, 3, 5])

In [ ]:
data.max()

6

In [ ]:
data.min()

1

In [ ]:
data.sum()

21

In [ ]:
#podemos agregar los valors de una matriz a lo largo de las columnas o
# a los largo de las filas usando el parametro axis. Si axis=0 se suma
# a los largo de las columnas si el axis= 1 se suma a lo largo de las
#filas

In [ ]:
data=np.array([[1, 2], [5, 3], [4, 6]])

data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [ ]:
data.max(axis=0)

array([5, 6])

In [ ]:
data.max(axis=1)


array([2, 5, 6])

In [ ]:
#si tienes dos matrices del mismo size puedes sumar y multiplicar las dos

data1= np.array([[1, 2], [3, 4]])
data2= np.array([[1, 1], [1, 1]])

data1 + data2

array([[2, 3],
       [4, 5]])

In [ ]:
#para multiplicar matrices tenemos dos opciones, o usamos el simbolo @
data1@data2

array([[3, 3],
       [7, 7]])

In [ ]:
#o la funcion dot
np.dot(data1, data2)

array([[3, 3],
       [7, 7]])

In [ ]:
#Puedes hacer estas operaciones matematicas en matrices de diferente sizes,
#pero solo si una de las matrices tiene solo una columna o una fila. En este
#caso,  NumPy usara la regla broadcast que vimos mas arriba.

In [ ]:
data1=np.array([[1, 2], [3, 4], [5, 6]])
data2=np.array([1,1])

data1 + data2

array([[2, 3],
       [4, 5],
       [6, 7]])

9.- GENERAR NUMEROS AL AZAR.
EL USO DE LA GENERACION ALEATORIA
DE NUMEROS ES FUNDAMENTAL EN LA CONFIGURACION DE ALGORITMOS
NUMERICOS Y DE MACHINE LEARNING. TAMBIEN EN LA INICIALIZACION ALEATORIA DE PESOS EN REDES NEURONALES ARTIFICIALES

In [ ]:
#Con Generator.integers, podemos generar integers aleatoriamente desde bajo
#(recuerda que este numero es incluido en NumPy) hasta alto (excluido).
#Podemos establecer el endpoint=True para incluir el numero alto.
#rng es la abreviatura de "Random Number Generator" en inglés,
#Podemos generar un 2 x 4 array de integers aleatorios entre 0 y 4 con:
#primero creamos el generador de numeros aleatorios
rng = np.random.default_rng()

rng.integers(8, size=(2, 14))

array([[1, 6, 0, 0, 0, 6, 0, 0, 3, 3, 2, 5, 5, 7],
       [4, 6, 0, 2, 1, 1, 3, 0, 5, 7, 2, 0, 3, 5]])

10.- COMO CONSEGUIR VALORES UNICOS Y CONTAR VALORES

In [ ]:
a= np.array([11, 11, 11, 11, 11, 11, 14, 16, 16, 16, 16, 16, 16, 16])
#usamos em metodo np.unique()

u=np.unique(a)

u

array([11, 14, 16])

In [ ]:
#para contar el numero de valores unicos

unicos, ocurren= np.unique(a, return_counts=True)

ocurren

array([6, 1, 7])

11.- TRANSPONER Y REFORMAR UNA MATRIZ

In [ ]:
#Transponer es pasar una matriz de 2x3  a 3x2, usamos reshape() y transpose()

In [ ]:
data.reshape(2, 3)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
data.reshape(3,2)

array([[1, 2],
       [5, 3],
       [4, 6]])

In [ ]:
a=np.arange(20)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#para invertir los axis de un array usamos transpose()

a=np.arange(20).reshape((5,4))

a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
a.transpose()

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [ ]:
#tambien podemos usar la T

a.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

12.-DARLE LA VUELTA A UN ARRAY

In [ ]:
#Usamos np.flip()

a= np.array([1, 2, 3, 4, 5, 6, 7, 8])

np.flip(a)



array([8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
#para un array 2D funciona parecido

a2=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

a2


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.flip(a2)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [ ]:
#puedes darle la vuelta solo a las filas

solofilas=np.flip(a2, axis=0)

solofilas

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [ ]:
#o puedes darle la vuelta solo a columnas

solocolumnas= np.flip(a2, axis=1)

solocolumnas

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

13.-APLANAR ARRAYS MULTIDIMENSIONALES

In [ ]:
#podemos usar el flatten() para convertir array multidimensional en 1D

x=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

x


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

14.-EL METODO numpy.linalg. Ofrece una amplia gama de operaciones y calculos en
algebra lineal como la resolucion de sistemas de ecuaciones lineales, calculo de la inversa de una matriz, etc

In [ ]:
#vamos a resolver un sistema de 3 ecuaciones lineales con 3 incognitas
#usando el metodo numpy.linalg.solve()

a= np.array([[2, 3, -1], [4, 1, 2], [3, -2, 1]]) #coeficientes de las variables

b= np.array([7, 4, 10]) #terminos independientes, detras del signo igual

#2x + 3y - z= 7
#4x + y + 2z= 4
#3x -2y + z= 10
x=np.linalg.solve(a, b)

x

array([ 3.74074074, -1.7037037 , -4.62962963])

In [ ]:
a=np.array([[2, 3], [4, 1]])

b= np.array([7, 4])

#2x + 3y = 7
#4x + y = 4

x=np.linalg.solve(a, b)

x

array([0.5, 2. ])

In [ ]:
import numpy as np
#La matriz inversa de una matriz cuadrada es la  matriz que cumple la propiedad
#de que al multiplicarla por A, se obtiene la matriz identidad I.

# Creamos una matriz
a = np.array([[1, 2], [3, 4]])

# Calcular la inversa de la matriz
a_inversa = np.linalg.inv(a)

# Mostrar la matriz original y su inversa
print("Matriz a:")
print(a)
print("\nInversa de la matriz a:")
print(a_inversa)

Matriz a:
[[1 2]
 [3 4]]

Inversa de la matriz a:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#Para comprobar que hemos calculado bien la matriz inversa de A
#vamos a multiplicar la matriz A por la matriz inversa y nos tiene que dar
#la matriz identidad que es una matriz cuadrada en la que los elementos de la
#diagonal son todos 1 y el resto de los elementos todos cero.
#Por ejemplo[1,0] [0, 1]

a=np.array([[1, 2], [3, 4]])
ainv=np.array([[-2, 1], [1.5, -0.5]])

a@ainv

array([[1., 0.],
       [0., 1.]])

15.- EJERCICIOS DE ARRAYS

In [ ]:
import numpy as np

# Crear dos matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Realizar la suma de las matrices
C = A + B

# Realizar la multiplicación elemento a elemento de las matrices
D = A * B

# Realizar la multiplicación matricial de las matrices
E = np.dot(A, B)

# Calcular la transpuesta de una matriz
F = A.T

# Mostrar los resultados
print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)
print("\nSuma de las matrices (A + B):")
print(C)
print("\nMultiplicación elemento a elemento (A * B):")
print(D)
print("\nMultiplicación matricial (A dot B):")
print(E)
print("\nTranspuesta de la matriz A:")
print(F)



Matriz A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz B:
[[10 11 12]
 [13 14 15]
 [16 17 18]]

Suma de las matrices (A + B):
[[11 13 15]
 [17 19 21]
 [23 25 27]]

Multiplicación elemento a elemento (A * B):
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]

Multiplicación matricial (A dot B):
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]

Transpuesta de la matriz A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
matriz = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [8, 8, 9]])

matriz

array([[1, 2, 3],
       [4, 5, 6],
       [8, 8, 9]])

In [ ]:
#nos va a dar error porque no todas las matrices tienen su inversa, las matrices
#singulares son cuadradas pero no tienen matriz inversa
matriz_inversa = np.linalg.inv(matriz)

matriz_inversa

array([[ 1.        , -2.        ,  1.        ],
       [-4.        ,  5.        , -2.        ],
       [ 2.66666667, -2.66666667,  1.        ]])

In [ ]:
#Para ver si una matriz es inversa usamos la funcion np.linalgdet()
#si nos da cero entonces la matriz es singular y no tiene inversa

matriz = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

det=np.linalg.det(matriz)

det

0.0

In [ ]:
#un ejemplo de una matriz no singular es

m= np.array([[2, 1, 3], [1, 0, 2], [3, 2, 1]])

inv=np.linalg.inv(m)

inv

array([[-1.33333333,  1.66666667,  0.66666667],
       [ 1.66666667, -2.33333333, -0.33333333],
       [ 0.66666667, -0.33333333, -0.33333333]])

16.- SUDOKU DE INDICES

In [ ]:
a=np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15],
    [16,17,18,19,20], [21,22,23,24,25], [26,27,28,29,30]])

a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
#calcula los indices de 11, 12, 16, 17
#calcula los indices de 2, 8, 14, 20
#calcula los indices de 4, 5, 24, 25, 29, 30

a[2:4, 0:2] #filas y columnas

array([[11, 12],
       [16, 17]])

In [ ]:
a[[0,1,2,3], [1,2,3,4]] #filas y columnas

array([ 2,  8, 14, 20])

In [ ]:
a[[0,4,5], 3:] #filas y columnas

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [ ]:
#EJERCICIOS SIN SOLUCION
#calcula los indices de 1, 5, 26, 30
#calcula los indices de 5, 10, 15, 20, 25, 30
#calcula los indices de 1, 7, 13, 19, 25
#calcula los indices de 26, 21, 16, 11, 6, 1
#calcula los indices de 11, 12, 13, 14, 15



In [ ]:
a[[0,0,5,5], [0,4,0,4]]

array([ 1,  5, 26, 30])

In [ ]:
a[[0,1,2,3,4,5], 4]

array([ 5, 10, 15, 20, 25, 30])

In [ ]:
a[[0,1,2,3,4], [0,1,2,3,4]]

array([ 1,  7, 13, 19, 25])