### MODELO BASICO DE CLASIFICACION DE IMAGENES

### RED NEURONAL DE UNA CAPA

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Datos de ejemplo para entrenar la red
# Supongamos que tenemos dos características de entrada (X) y una salida (y)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 0, 0, 1])

# Creación del modelo de red neuronal de una sola capa
model = keras.Sequential([
    layers.Dense(units=1, input_shape=(2,), activation='sigmoid')
])

# Compilación del modelo
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

# Entrenamiento del modelo
model.fit(X, y, epochs=1000, verbose=0)

# Predicciones con el modelo entrenado
predictions = model.predict(X)
rounded_predictions = np.round(predictions)

# Resultados
print("Predicciones:")
print(predictions)
print("Predicciones redondeadas:")
print(rounded_predictions)

1/1 [==============================] - 0s 73ms/step
Predicciones:
[[0.16841933]
 [0.3011147 ]
 [0.3218207 ]
 [0.50236464]]
Predicciones redondeadas:
[[0.]
 [0.]
 [0.]
 [1.]]


In [ ]:
#En este ejemplo, se utiliza un modelo simple de red neuronal con dos capas
#densas (fully connected layers) para resolver el problema XOR. Los datos de
#entrenamiento consisten en las entradas [0, 0], [0, 1], [1, 0], [1, 1] y las
#salidas esperadas [0, 1, 1, 0]. El modelo se entrena durante 1000 épocas
#utilizando el optimizador Adam y la función de pérdida binary crossentropy.

#Una vez entrenado, el modelo se evalúa utilizando los mismos datos de prueba y
#se muestra la precisión obtenida.


import tensorflow as tf
from tensorflow import keras
import numpy as np

# Datos de entrenamiento
x_train = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_train = np.array([0, 1, 1, 0], dtype=np.float32)

# Definir el modelo
modelo = keras.Sequential([
    keras.layers.Dense(2, input_shape=(2,), activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

# Compilar el modelo
modelo.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Entrenar el modelo
modelo.fit(x_train, y_train, epochs=10)

# Datos de prueba
x_test = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_test = np.array([0, 1, 1, 0], dtype=np.float32)

# Evaluar el modelo
resultado = modelo.evaluate(x_test, y_test)
print("Precisión de la prueba:", resultado[1])

Epoch 1/10
1/1 [==============================] - 1s 648ms/step - loss: 0.6897 - accuracy: 0.7500
Epoch 2/10
1/1 [==============================] - 0s 13ms/step - loss: 0.6897 - accuracy: 0.7500
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 0.6897 - accuracy: 0.7500
Epoch 4/10
1/1 [==============================] - 0s 11ms/step - loss: 0.6896 - accuracy: 0.7500
Epoch 5/10
1/1 [==============================] - 0s 12ms/step - loss: 0.6896 - accuracy: 0.7500
Epoch 6/10
1/1 [==============================] - 0s 9ms/step - loss: 0.6895 - accuracy: 0.7500
Epoch 7/10
1/1 [==============================] - 0s 9ms/step - loss: 0.6895 - accuracy: 0.7500
Epoch 8/10
1/1 [==============================] - 0s 9ms/step - loss: 0.6894 - accuracy: 0.7500
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: 0.6894 - accuracy: 0.7500
Epoch 10/10
1/1 [==============================] - 0s 10ms/step - loss: 0.6893 - accuracy: 0.7500


1/1 [==============================] - 0s 134ms/step - loss: 0.6893 - accuracy: 0.7500
Precisión de la prueba: 0.75


Este ejemplo carga el conjunto de datos MNIST (es una enorme base de datos de dígitos escritos manualmente que se utiliza normalmente para preparar diferentes sistemas de manejo de imágenes. Además, la base de datos se utiliza generalmente para la preparación y el ensayo en el campo del aprendizaje por máquina),  normaliza las imágenes de entrada y codifica las etiquetas en un formato one-hot(La codificación One-Hot es un método para etiquetar a qué clase pertenecen los datos y la idea es asignar 0 a toda la dimensión, excepto 1 para la clase a la que pertenecen los datos). Luego, se construye un modelo de red neuronal secuencial con una capa de entrada, una capa oculta y una capa de salida. El modelo se compila con un optimizador "adam" y una función de pérdida de entropía cruzada categórica (Adam combina las ideas de dos métodos de optimización, el descenso de gradiente estocástico [SGD, por sus siglas en inglés] y el estimador de momentos adaptativos [RMSProp], Utiliza una estimación adaptativa de los momentos de primer y segundo orden del gradiente para actualizar los parámetros del modelo de manera eficiente).

SGD es un algoritmo en el que los parámetros del modelo se actualizan en función del gradiente de la función de pérdida calculado en una muestra de datos aleatoria (un subconjunto de los datos de entrenamiento). A diferencia del descenso de gradiente clásico, que calcula el gradiente en función de todos los datos de entrenamiento, el SGD realiza actualizaciones más frecuentes y utiliza menos datos en cada iteración

RMSProp (se utiliza como un algoritmo de optimización para mejorar el entrenamiento de redes neuronales. Ajusta el ritmo de aprendizaje de forma adaptativa para cada parámetro basándose en los promedios de los gradientes anteriores. Esto puede ayudar a acelerar el proceso de convergencia y a mejorar el rendimiento del modelo durante el entrenamiento).

A continuación, se entrena el modelo durante 5 épocas utilizando un tamaño de lote de 32 y se evalúa su rendimiento utilizando los datos de prueba. Al finalizar, se imprime la pérdida y la precisión obtenida.

Este es solo un ejemplo básico para darte una idea de cómo se utiliza TensorFlow para construir una red neuronal simple.

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

# Cargar los datos de entrenamiento y prueba de MNIST
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Preprocesamiento de los datos
x_train = x_train / 255.0
x_test = x_test / 255.0

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

# Construir el modelo de red neuronal
model = Sequential()
model.add(Flatten(input_shape=(28, 28)))  # Capa de entrada
model.add(Dense(128, activation='relu'))  # Capa oculta
model.add(Dense(10, activation='softmax'))  # Capa de salida

# Compilar el modelo
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Entrenar el modelo
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_test, y_test))

# Evaluar el modelo con los datos de prueba
loss, accuracy = model.evaluate(x_test, y_test)
print(f'Loss: {loss}')
print(f'Accuracy: {accuracy}')

11490434/11490434 [==============================] - 0s 0us/step
Epoch 1/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.2574 - accuracy: 0.9266 - val_loss: 0.1386 - val_accuracy: 0.9602
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1110 - accuracy: 0.9675 - val_loss: 0.0985 - val_accuracy: 0.9695
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0746 - accuracy: 0.9777 - val_loss: 0.0906 - val_accuracy: 0.9716
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0569 - accuracy: 0.9822 - val_loss: 0.0782 - val_accuracy: 0.9752
Epoch 5/5
313/313 [==============================] - 1s 2ms/step - loss: 0.0807 - accuracy: 0.9757
Loss: 0.0807201936841011
Accuracy: 0.9757000207901001


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Crear un modelo secuencial
model = Sequential()

# Agregar capas al modelo
model.add(Dense(64, activation='relu', input_shape=(100,)))
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))

In [ ]:
import tensorflow as tf
from tensorflow.keras.utils import to_categorical

# Etiquetas de entrada
labels = [0, 1, 2, 1, 0]

# Convertir etiquetas a representación one-hot
one_hot_labels = to_categorical(labels, num_classes=3)

print(one_hot_labels)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

# Cargar los datos de MNIST
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Preprocesamiento de los datos
x_train = x_train / 255.0
x_test = x_test / 255.0

# Definir el modelo de red neuronal
model = Sequential([
    Flatten(input_shape=(28, 28)),  # Aplanar la imagen 28x28 a un vector de 784
    Dense(128, activation='relu'),  # Capa oculta con 128 neuronas y función de activación ReLU
    Dense(10, activation='softmax')  # Capa de salida con 10 neuronas (una por cada clase) y función de activación softmax
])

# Compilar el modelo
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Entrenar el modelo
model.fit(x_train, y_train, epochs=5, batch_size=32, verbose=1)

# Evaluar el modelo en los datos de prueba
loss, accuracy = model.evaluate(x_test, y_test, verbose=2)
print('Precisión en los datos de prueba:', accuracy)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2596 - accuracy: 0.9268
Epoch 2/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1145 - accuracy: 0.9657
Epoch 3/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0775 - accuracy: 0.9769
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0568 - accuracy: 0.9827
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0448 - accuracy: 0.9860
313/313 - 1s - loss: 0.0806 - accuracy: 0.9746 - 684ms/epoch - 2ms/step
Precisión en los datos de prueba: 0.9746000170707703


### IMPLEMENTACION DE RED NEURONAL


In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_openml

import tensorflow as tf
from tensorflow.keras.models import Sequential #clase de Keras para construir
#red neuronal capa por capa
from tensorflow.keras.layers import Dense #clase de Keras para crear capa red
#neuronal  completamente conectada

In [ ]:
#cargar el conjunto de datos Pim Indians Diabetes
dataset=fetch_openml(name='diabetes')

#extraer las caracteristicas y las etiquetas
X = dataset['data']
y = dataset['target'].astype(np.int)

#dividir los datos en conjuntos de entrenamiento y de prueba
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:301: UserWarning: Multiple active versions of the dataset matching the name diabetes exist. Versions may be fundamentally different, returning version 1.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(
<ipython-input-6-8891d02a4997>:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If yo

ValueError: ignored

In [ ]:
#Crear un modelo que esta compuesto por una pila lineal de capas
model=Sequential()

#Añadir la primera capa densa con 16 neuronas donde cada neurona recibe un
#un vector de 8 elementos como entrada (esas entradas pueden venir de una capa
#anterior o ser las caracteristicas de entrada del modelo si es la primera capa)
#y una funcion de activacion ReLu
#esos 8 elementos del vector podrian ser las caracteristicas de las que
#depende el valor de una casa (tamaño, numero de habitaciones, ubicacion, año
#de construccion
model.add(Dense(16, input_dim=8, activation='relu'))

#Añadir la segunda capa densa, no hace falta repetir input_dim= ya que
#las capas siguientes infieren su forma de entrada de la capa anterior

model.add(Dense(8, activation='relu'))

#Añadir la capa de salida

model.add(Dense(1, activation='sigmoid'))

#Las funciones de activación son una parte esencial de las redes neuronales.
#Son lo que permite a las redes neuronales modelar relaciones complejas y no
#lineales entre las entradas y las salidas. Las funciones de activación se
#aplican a las salidas de las neuronas de una capa antes de pasarlas a la
#siguiente capa.
#La red neuronal utiliza la función de activación ReLU en las primeras y
#segundas capas para aprender características complejas y la función de
#activación Sigmoid en la última capa para producir una probabilidad de clase.
#Esta es una configuración común para las redes neuronales en tareas de
#clasificación binaria.

#Una vez que hemos creado la arquitectura de la red necesitamos compilar el
#modelo
#"Compilar" en el contexto de las redes neuronales se refiere a la etapa en la
#que se define cómo se va a entrenar la red. Esto incluye definir la función de
#pérdida, que es la medida de error que el algoritmo intentará minimizar,
#definir el optimizador, que es el método que se utilizará para minimizar la
#función de pérdida, y definir las métricas, que son las medidas de rendimiento
#que se seguirán a lo largo del entrenamiento.
#Esencialmente, al compilar, estás configurando la red neuronal para el
#aprendizaje, especificando las reglas y las herramientas que utilizará para
#ajustarse a tus datos.

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

#Asumimos que X_train e y_train son los datos de entrenamiento y entrenamos el
#modelo

model.fit(x_train, y_train, epochs=150, batch_size=10)

#Por último evaluamos el modelo en los datos de prueba X_test e y_test

loss, accuracy=model.evaluate(x_test, y_test)

print('Accuracy: %.2f' %(accuracy*100))

NameError: ignored

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_openml
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Cargar el conjunto de datos Pima Indians Diabetes
dataset = fetch_openml(name='diabetes')

# Extraer las características y las etiquetas
X = dataset['data']
y= np.where(dataset['target'] =='tested_positive, 1, 0')

# Dividir los datos en conjuntos de entrenamiento y prueba
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Definir el modelo
model = Sequential()
model.add(Dense(16, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Compilar el modelo
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Entrenar el modelo
model.fit(x_train, y_train, epochs=150, batch_size=10)

# Evaluar el modelo
loss, accuracy = model.evaluate(x_test, y_test)
print('Accuracy: %.2f' %(accuracy*100))

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:301: UserWarning: Multiple active versions of the dataset matching the name diabetes exist. Versions may be fundamentally different, returning version 1.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


ValueError: ignored